ALTER TABLE HOTEL
ADD CONSTRAINT RATING_CONSTRAINT CHECK (
	RATING >= 1
	AND RATING <= 5
);

ALTER TABLE ROOM
ADD CONSTRAINT CAPACITY_CONSTRAINT CHECK (
	CAPACITY >= 1
);

ALTER TABLE BOOKING
ADD CONSTRAINT BOOKING_TIMES_CONSTRAINT CHECK (
	(START_DATE || ' ' || START_TIME)::TIMESTAMP < (END_DATE || ' ' || END_TIME)::TIMESTAMP
);

ALTER TABLE BOOKING
ADD CONSTRAINT BOOKING_STATUS_CONSTRAINT CHECK (
	STATUS IN ('pending', 'active', 'completed', 'cancelled')
);